django/django 8일차/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    # path("new/", views.new, name="new"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update", views.update, name="update"),
]

django/django 8일차/articles/models.py
from django.db import models

# Create your models here.
"""
게시판 기능
- 제목(50글자이내)
- 내용(긴 글)
- 글 작성시간/수정시간(자동으로 기록, 날짜/기록)
"""


class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

django/django 8일차/articles/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content"]

django/django 8일차/articles/views.py
from django.shortcuts import render, redirect
from articles.models import Article
from .forms import ArticleForm

# Create your views here.
def index(request):
    articles = Article.objects.order_by("-pk")
    context = {"articles": articles}
    return render(request, "articles/index.html", context)


# def new(request):
#     article_form = ArticleForm()
#     context = {
#         "article_form": article_form,
#     }
#     return render(request, "articles/new.html", context=context)


def create(request):
    # title = request.POST.get("title")
    # content = request.POST.get("content")
    # Article.objects.create(title=title, content=content)
    # return redirect("articles:index")
    if request.method == "POST":
        # DB에 저장하는 로직
        article_form = ArticleForm(request.POST)
        if article_form.is_valid():
            article_form.save()
            return redirect("articles:index")
    else:
        article_form = ArticleForm()
    context = {"article_form": article_form}
    return render(request, "articles/new.html", context=context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)

    context = {
        "article": article,
    }
    return render(request, "articles/detail.html", context)


def update(request, pk):
    # GET : Form을 제공
    article = Article.objects.get(pk=pk)
    # article_form = ArticleForm(instance=article)
    if request.method == "POST":
        # POST : input 값 가져와서, 검증하고, DB에 저장
        article_form = ArticleForm(request.POST, instance=article)
        if article_form.is_valid():
            # 유효성 검사 통과하면 저장하고, 상세보기 페이지로
            article_form.save()
            return redirect("articles:detail", article.pk)
        # 유효성 검사 통과하지 않으면 => context 부터해서 오류메시지 담긴 article_form을 랜더링
    else:
        # GET : Form을 제공
        article_form = ArticleForm(instance=article)
    context = {
        "article_form": article_form,
    }
    return render(request, "articles/update.html", context)

django/django 8일차/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %} 
<h1>{{ article.pk }}번 게시글</h1>
<p>{{ article.created_at }} | {{ article.updated_at }}</p>
<p>{{ article.content }} </p>
<a href="{% url 'articles:update' article.pk %}">수정하기</a>
{% endblock %}

django/django 8일차/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}
{% block body %} 
<h1>게시판</h1>
<img src="{% static 'images/img2.jpg' %}" alt="">
<a href="{% url 'articles:create' %}">글 쓰기</a>
{% for article in articles %}
<h3><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></h3>
<p>{{ article.created_at }} | {{ article.updated_at }}</p>
<hr>
{% endfor %}
{% endblock %}

django/django 8일차/articles/templates/articles/new.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
<h1>글쓰기</h1>

<!-- form : 사용자에게 양식을 제공하고
  값을 받아서(input : new, value)
  서버에 전송(form : action) -->

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form article_form %}
  {# article_form.as_p #}
  <!-- <label for="title">제목 : </label>
  <input type="text" name="title" id="title">
  <textarea name="content" id="content" cols="30" rows="10"></textarea> -->
  {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock %}

django/django 8일차/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<h1>글 수정하기</h1>

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form article_form %}
  {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock %}
</form>