django/django 11일차/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("<int:pk>/", views.detail, name="detail"),
    path("list", views.list, name="list"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

django/django 11일차/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username",)

django/django 11일차/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout

# Create your views here.
def index(request):
    return render(request, "accounts/index.html")


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()  # ModelForm의 save 메서드의 리턴값은 해당 모델의 인스턴스다!
            auth_login(request, user)  # 로그인
            return redirect("accounts:index")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        # AuthenticationForm은 ModelForm이 아님!
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # 세션에 저장
            # login 함수는 request, user 객체를 인자로 받음
            # user 객체는 어디있어요? 바로 form에서 인증된 유저 정보를 받을 수 있음
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "accounts:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/detail.html", context)


def list(request):
    user = get_user_model().objects.order_by("-pk")
    context = {
        "user": user,
    }
    return render(request, "accounts/list.html", context)


def logout(request):
    auth_logout(request)
    return redirect("accounts:index")

django/django 11일차/accounts/templates/accounts/detail.html
<h1>{{ user.username }}님의 프로필</h1>

django/django 11일차/accounts/templates/accounts/index.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}
{% endblock %}
{% block body %}
  <h1>{{ user }}</h1>
  {% if request.user.is_authenticated %}
  <span>{{ request.user }}</span>
  <a href="{% url 'accounts:logout' %}">로그아웃</a>
  {% else %}
  <a href="{% url 'accounts:login' %}">로그인</a>
  {% endif %}
  <form action="" method='post'>
    {% csrf_token %}
    {% comment %} {% bootstrap_form form %} {% endcomment %}
    {% comment %} {{ review_form.as_p }} {% endcomment %}
    <a href="{% url 'accounts:signup' %}">
      회원가입
    </a>
    <a href="{% url 'accounts:list' %}">
      회원목록
    </a>
  </form>
{% endblock %}

{% bootstrap_javascript %}

django/django 11일차/accounts/templates/accounts/list.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}{% endblock %}
{% block body %}
  <h1>회원목록</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">username</th>
      </tr>
    </thead>
    {% for users in user %}
      <tbody>

        <tr>
          <td>{{ users.pk }}</td>
          <td>
            <a href="{% url 'accounts:detail' users.pk %}">
              {{ users.username }}
            </td>
          </tr>
        </tbody>
      {% endfor %}
    </table>
  {% endblock %}

  {% bootstrap_javascript %}

django/django 11일차/accounts/templates/accounts/login.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}{% endblock %}
{% block body %}
  <h1>로그인</h1>

  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% comment %} {{ review_form.as_p }} {% endcomment %}
    {% bootstrap_button button_type="submit" content="OK" %}
  </form>
{% endblock %}
{% bootstrap_javascript %}

django/django 11일차/accounts/templates/accounts/signup.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}
{% endblock %}
{% block body %}
  <h1>회원가입</h1>

  <form action="" method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% comment %} {{ review_form.as_p }} {% endcomment %}
    {% bootstrap_button button_type="submit" content="작성" %}
  </form>
{% endblock %}
{% bootstrap_javascript %}