django/django 16일차/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"


urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("update/", views.update, name="update"),
]

django/django 16일차/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

django/django 16일차/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "email",
        )

django/django 16일차/accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect

# from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from articles.models import Article

# Create your views here.
def index(request):
    user = get_user_model().objects.order_by("-pk")
    context = {
        "user": user,
    }
    return render(request, "accounts/index.html", context)


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:index")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        # AuthenticationForm은 ModelForm이 아님!
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # 세션에 저장
            # login 함수는 request, user 객체를 인자로 받음
            # user 객체는 어디있어요? 바로 form에서 인증된 유저 정보를 받을 수 있음
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "accounts:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("accounts:index")


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    article = Article.objects.get(pk=pk)
    context = {
        "user": user,
        "article": article,
    }
    return render(request, "accounts/detail.html", context)


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)

django/django 16일차/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}{% endblock %}
{% block body %}
  <a href="{% url 'accounts:update' %}">
    <h1>{{ user.username }}님의 프로필</h1>
  </a>
  <p>{{ user.email }}</p>
  <p>{{ user.last_name }}
    |
    {{ user.first_name }}</p>
  <h3>작성한 글</h3>
  {% for article in user.article_set.all %}
    <h3>{{ article.pk }}</h3>
    <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
  {% endfor %}
{% endblock body %}
{% bootstrap_javascript %}

django/django 16일차/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}{% endblock %}
{% block body %}
  <h1>회원목록</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">username</th>
      </tr>
    </thead>
    {% for users in user %}
      <tbody>

        <tr>
          <td>{{ users.pk }}</td>
          <td>
            <a href="{% url 'accounts:detail' users.pk %}">
              {{ users.username }}
            </td>
          </tr>
        </tbody>
      {% endfor %}
    </table>
  {% endblock body %}
  {% bootstrap_javascript %}

django/django 16일차/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}
{% endblock %}
{% block body %}
  <h1>로그인</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% comment %} {{ review_form.as_p }} {% endcomment %}
    {% bootstrap_button button_type="submit" content="OK" %}
  </form>

{% endblock body %}
{% bootstrap_javascript %}

django/django 16일차/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}
{% endblock %}
{% block body %}
  <h1>회원가입</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% comment %} {{ review_form.as_p }} {% endcomment %}
    {% bootstrap_button button_type="submit" content="OK" %}
  </form>

{% endblock body %}
{% bootstrap_javascript %}

django/django 16일차/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% block css %}
{% endblock %}
{% block body %}
  <h1>프로필 업데이트</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% comment %} {{ review_form.as_p }} {% endcomment %}
    {% bootstrap_button button_type="submit" content="OK" %}
  </form>

{% endblock body %}
{% bootstrap_javascript %}