django/django 9일차/movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
]

django/django 9일차/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=50)
    summary = models.TextField()
    running_time = models.IntegerField()

django/django 9일차/movies/forms.py
from socket import fromshare
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = [
            "title",
            "summary",
            "running_time",
        ]

django/django 9일차/movies/views.py
from django.shortcuts import render, redirect
from movies.models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movies = Movie.objects.order_by("-pk")
    context = {
        "movies": movies,
    }
    return render(request, "movies/index.html", context)


def create(request):
    if request.method == "POST":
        # DB에 저장하는 로직
        movie_form = MovieForm(request.POST)
        if movie_form.is_valid():
            movie_form.save()
            return redirect("movies:index")
    else:
        movie_form = MovieForm()
    context = {
        "movie_form": movie_form,
    }
    return render(request, "movies/new.html", context=context)


def detail(request, pk):
    # 특정 글을 가져온다.
    movie = Movie.objects.get(pk=pk)
    # template에 객체 전달
    context = {
        "movie": movie,
    }
    return render(request, "movies/detail.html", context)


def update(request, pk):
    # GET : Form을 제공
    movie = Movie.objects.get(pk=pk)
    # movie_form = MovieForm(instance=movie)
    if request.method == "POST":
        # POST : input 값 가져와서, 검증하고, DB에 저장
        movie_form = MovieForm(request.POST, instance=movie)
        if movie_form.is_valid():
            # 유효성 검사 통과하면 저장하고, 상세보기 페이지로
            movie_form.save()
            return redirect("movies:detail", movie.pk)
        # 유효성 검사 통과하지 않으면 => context 부터해서 오류메시지 담긴 article_form을 랜더링
    else:
        # GET : Form을 제공
        movie_form = MovieForm(instance=movie)
    context = {
        "movie_form": movie_form,
    }
    return render(request, "movies/update.html", context)


def delete(request, pk):
    # pk에 해당하는 글 삭제
    movie = Movie.objects.get(id=pk)
    movie.delete()
    return redirect("movies:index")

django/django 9일차/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block body %}
  <div>
    <div class='d-flex'>
      <h1>{{ movie.title }}</h1>
      <h3>{{ movie.running_time }}</h3>
    </div>
    <p>{{ movie.summary }}</p>
    <a href="{% url 'movies:update' movie.pk %}">수정</a>
    <a href="{% url 'movies:delete' movie.pk %}">삭제</a>
  </div>
{% endblock %}

django/django 9일차/movies/templates/movies/index.html
{% extends 'base.html' %}
{% block body %}
  <h1>게시판</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">pk</th>
        <th scope="col">영화제목</th>
        <th scope="col">상영시간</th>
      </tr>
    </thead>
    {% for movie in movies %}
      <tbody>
        <tr>
          <td>{{ movie.pk }}</td>
          <td>
            <a href="{% url 'movies:detail' movie.pk %}">
              {{ movie.title }}
            </a>
          </td>
          <td>{{ movie.running_time }}</td>
        </tr>
      </tbody>
    {% endfor %}
  </table>
{% endblock %}

django/django 9일차/movies/templates/movies/new.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
<h1>글쓰기</h1>
<form action="{% url 'movies:create' %}" method='post'>
  {% csrf_token %}
  {% bootstrap_form movie_form %}
  {% comment %} {{ movie_form.as_p }} {% endcomment %}
  {% bootstrap_button button_type="submit" content="글쓰기" %}
</form>
{% endblock %}

django/django 9일차/movies/templates/movies/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>글 수정하기</h1>

  <form action="" method='post'>
    {% csrf_token %}
    {% bootstrap_form movie_form %}
    {% comment %} {{ movie_form.as_p }} {% endcomment %}
    {% bootstrap_button button_type="submit" content="수정" %}
  </form>
{% endblock %}
</form>